version: '3'
services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile-auth
    container_name: auth-service
    image: auth-service
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - user-service

  user-service:
    build:
      context: .
      dockerfile: Dockerfile-user
    container_name: user-service
    image: user-service
    ports:
      - '8081:8081'
    depends_on:
      - postgres

  class-service:
    build:
      context: .
      dockerfile: Dockerfile-class
    container_name: class-service
    image: class-service
    ports:
      - '8082:8082'
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - '5432:5432'


volumes:
  postgres:
    driver: local